#!/bin/sh
BALANCE=$(/usr/local/bin/chaincoind getinfo | grep -m 1 balance)
IPADDR=$(ifconfig eth0 | grep -oP 'inet addr:\K\S+')
STATUS=$(/usr/local/bin/chaincoind masternodelist status $IPADDR|grep -m 1 "$IPADDR")
MNADDRESS="CTCJM7BHzrSYuR4QYYYcsDLxfe2mNxE2pg"

printf "\n$(tput setf 2)Masternode $BALANCE$(tput sgr0)"
printf "\n$(tput setf 3)Status:$STATUS$(tput sgr0)\n"

printf "\n\n$(tput setf 1)Donations:\t$MNADDRESS$(tput sgr0)\n\n"
